openapi: 3.0.0
info:
  title: OpenAPI Sample
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './schemas/test.json'